# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa1589e2c7ba53f504f86495be7c646e91e50f0d76d29a2d0c3477dcba92e719e0d8285eae7585de6442e6184617da9e29e8f7c968c1d5362af993823edd427a

test:
  secret_key_base: 13929a136fafe67d74c3e9804cfa18aecc6ef1b3c7962f8dc77e53bcf985a23536e185b7e85a5ae281df747a0f47dfa118955d39e2541fe72b07578a187d35dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
